name: dev

on: push

jobs:
  dev:
    runs-on: ubunt-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup Dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.x
      - name: Execute dotnet Build
        run: dotnet build Notify

