name: Open PR Stagging
on:
  push:
    branches:
      - 'feature/**'

env:
    GH_TOKEN: ${{ secrets.ACTIONS_TOKEN }}


jobs:
   open_pr:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v3
        - name: open-pull-request
          run: |
            gh pr create --title "PR Automático de ${GITHUB_REF##*/} para Stagging " --body "Description" -B "stagging" 
      
